//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADAMasan.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaiDatCaSanXuat
    {
        public int Id { get; set; }
        public string TruongCa1 { get; set; }
        public string TruongCa2 { get; set; }
        public string TruongCa3 { get; set; }
        public Nullable<int> HourCa1 { get; set; }
        public Nullable<int> MinuteCa1 { get; set; }
        public Nullable<int> HourCa2 { get; set; }
        public Nullable<int> MinuteCa2 { get; set; }
        public Nullable<int> HourCa3 { get; set; }
        public Nullable<int> MinuteCa3 { get; set; }
    }
}
