//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADAMasan.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public string SanPham { get; set; }
        public Nullable<int> CaSanXuat { get; set; }
        public Nullable<int> DayChuyen { get; set; }
        public Nullable<int> MaySo { get; set; }
        public Nullable<int> TongSoGoi { get; set; }
        public Nullable<int> SoGoiCan { get; set; }
        public Nullable<int> SoGoiRong { get; set; }
    }
}
