//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADAMasan.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSo
    {
        public int Id { get; set; }
        public Nullable<int> DayChuyenSo { get; set; }
        public Nullable<int> MaySo { get; set; }
        public string SanPham { get; set; }
        public Nullable<int> CaSanXuat { get; set; }
        public Nullable<int> TocDoChuan { get; set; }
        public Nullable<int> TimeDungMay { get; set; }
        public Nullable<int> TimeChapNhanGoi { get; set; }
        public Nullable<int> TimeTinhGoiCan { get; set; }
        public Nullable<int> TimeDayGoiCan { get; set; }
        public Nullable<int> TimeUpdatePLC { get; set; }
        public Nullable<int> TimeXilanhDayGoi { get; set; }
    }
}
